# Generated by Django 6.0.5 on 2026-05-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.DateField(),
        ),
    ]
