# Generated by Django 6.0.5 on 2026-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('review', 'Review')], default='booking', max_length=20),
        ),
    ]
